[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_hello_world = "7oZAwjFYYAohXSfpkNDrSZmEZi4TJxz5fRutmaB7Ss8H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "/Users/esad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
